- name: Create Home directory for Photoprism
  file:
    path: /home/kevin/photoprism
    state: directory
   
- name: Create Docker Compose file for Photoprism
  copy:
    src: templates/docker-compose.yml
    dest: /home/kevin/photoprism/docker-compose.yml
    
