- name: Create Home directory for Photoprism
  file:
    path: /home/{{ utente }}/photoprism
    state: directory
   
- name: Create Docker Compose file for Photoprism
  template:
    src: templates/docker-compose.yml
    dest: /home/{{ utente }}/photoprism/docker-compose.yml
    
