- name: Create Home directory for Scripts
  file:
    path: /home/kevin/scripts
    state: directory
    
- name: Create file for Scripts
  copy:
    src: templates/mount_samba.sh
    dest: /home/kevin/scripts/mount_samba.sh

- name: Create file for rsync_user
  copy:
    src: templates/rsync_user.sh
    dest: /home/kevin/scripts/rsync_user.sh
    
- name: Create file for rsync_root
  copy:
    src: templates/rsync_root.sh
    dest: /home/kevin/scripts/rsync_root.sh
    
- name: Add task to user crontab
  cron:
    name: "RSYNC FOTO E VIDEO"
    user: "kevin"
    minute: "0"
    hour: "9"
    job: "/home/kevin/scripts/rsync_user.sh"

- name: Add task to root crontab
  cron:
    name: "RSYNC FOTO E VIDEO"
    user: "root"
    minute: "0"
    hour: "21"
    job: "/home/kevin/scripts/rsync_root.sh"

- name: Set permissions of file to be executable
  command: chmod +x /home/kevin/scripts/rsync_user.sh
- name: Set permissions of file to be executable
  command: chmod +x /home/kevin/scripts/rsync_root.sh

- name: Set permissions of file to be executable
  file:
    path: /home/kevin/scripts/rsync_user.sh
    mode: "755"
    state: file

- name: Set permissions of file to be executable
  file:
    path: /home/kevin/scripts/rsync_root.sh
    mode: "755"
    state: file

- name: Add task to root crontab
  cron:
    name: "SHUTDOWN "
    user: "root"
    minute: "30"
    hour: "23"
    job: "/usr/sbin/shutdown -h now"
