- name: Create Home directory for Scripts
  file:
    path: /home/{{ utente }}/scripts
    state: directory

- name: Create file for credentials
  template:
    src: templates/.smbcredentials
    dest: /home/{{ utente }}/.smbcredentials

- name: Create file for rsync_user
  template:
    src: templates/rsync_user.sh
    dest: /home/{{ utente }}/scripts/rsync_user.sh
    
- name: Create file for rsync_root
  template:
    src: templates/rsync_root.sh
    dest: /home/{{ utente }}/scripts/rsync_root.sh
    
- name: Add task to user crontab
  cron:
    name: "RSYNC FOTO E VIDEO"
    user: "root"
    minute: "0"
    hour: "11"
    job: "/home/{{ utente }}/scripts/rsync_user.sh"

- name: Add task to root crontab
  cron:
    name: "RSYNC FOTO E VIDEO"
    user: "root"
    minute: "0"
    hour: "18"
    job: "/home/{{ utente }}/scripts/rsync_root.sh"

- name: Set permissions of file to be executable
  command: chmod +x /home/{{ utente }}/scripts/rsync_user.sh
- name: Set permissions of file to be executable
  command: chmod +x /home/{{ utente }}/scripts/rsync_root.sh

- name: Set permissions of file to be executable
  file:
    path: /home/{{ utente }}/scripts/rsync_user.sh
    mode: "755"
    state: file

- name: Set permissions of file to be executable
  file:
    path: /home/{{ utente }}/scripts/rsync_root.sh
    mode: "755"
    state: file

- name: Add task to root crontab
  cron:
    name: "SHUTDOWN "
    user: "root"
    minute: "30"
    hour: "23"
    job: "/usr/sbin/shutdown -h now"
