- name: Create Home directory for Scripts
  file:
    path: /home/kevin/scripts
    state: directory
    
- name: Create file for Scripts
  copy:
    src: templates/mount_samba.sh
    dest: /home/kevin/scripts/mount_samba.sh

- name: Create file for rsync_user
  copy:
    src: templates/rsync_user.sh
    dest: /home/kevin/scripts/rsync_user.sh
    
- name: Create file for rsync_root
  copy:
    src: templates/rsync_root.sh
    dest: /home/kevin/scripts/rsync_root.sh
    
- name: Add task to user crontab
  cron:
    name: "Task name"
    user: "kevin"
    minute: "0"
    hour: "9"
    job: "bash /home/kevin/scripts/rsync_user.sh"

- name: Add task to root crontab
  cron:
    name: "Task name"
    user: "root"
    minute: "0"
    hour: "21"
    job: "/home/kevin/scripts/rsync_root.sh"
