---
version: "3.7"
services:
  motioneye:
    container_name: motioneye
    image: ccrisan/motioneye:master-armhf
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/home/{{ utente }}/motioneye:/etc/motioneye"
    - "/home/{{ utente }}/motioneye/storage:/var/lib/motioneye"
    network_mode: host
    restart: always