- name: Installa pacchetti necessari
  apt:
    name: "{{ cockpit_packages }}"
    state: present
    update_cache: yes

- name: Download cockpit-navigator package
  get_url:
    url: "https://github.com/45Drives/cockpit-navigator/releases/download/v{{ cockpit_navigator_version }}/cockpit-navigator_{{ cockpit_navigator_version }}-1focal_all.deb"
    dest: "/tmp/cockpit-navigator.deb"

- name: Installa cockpit-navigator package
  apt:
    deb: "/tmp/cockpit-navigator.deb"

- name: Download cockpit-samba-manager package
  get_url:
    url: "https://github.com/45Drives/cockpit-samba-manager/releases/download/v{{ cockpit_samba_manager_version }}/cockpit-samba-manager_{{ cockpit_samba_manager_version }}-1focal_all.deb"
    dest: "/tmp/cockpit-samba-manager.deb"

- name: Installa cockpit-samba-manager package
  apt:
    deb: "/tmp/cockpit-samba-manager.deb"

- name: Aggiungi sezione registry in smb.conf
  lineinfile:
    path: "/etc/samba/smb.conf"
    line: 'include = registry'
    state: present
    insertafter: '\[global\]'

- name: Riavvia i servizi necessari
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - smbd
    - cockpit.socket

- name: Abilita e avvia il servizio Cockpit
  service:
    name: cockpit
    state: started
    enabled: true

- name: Verifica stato del servizio Cockpit
  command: systemctl status cockpit
  register: cockpit_status

- debug:
    var: cockpit_status.stdout
