- name: Installazione e configurazione di Cockpit
  hosts: target
  become: true
  tasks:
    - name: Installa pacchetti necessari
      apt:
        name:
          - dpkg
          - cockpit
          - ntfs-3g
          - samba
        state: present
        update_cache: yes

    - name: Download cockpit-navigator package
      get_url:
        url: "https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.10/cockpit-navigator_0.5.10-1focal_all.deb"
        dest: "/tmp/cockpit-navigator.deb"

    - name: Installa cockpit-navigator package
      apt:
        deb: "/tmp/cockpit-navigator.deb"
      become: true

    - name: Download cockpit-samba-manager package
      get_url:
        url: "https://github.com/45Drives/cockpit-samba-manager/releases/download/v1.0.6/cockpit-samba-manager_1.0.6-1focal_all.deb"
        dest: "/tmp/cockpit-samba-manager.deb"

    - name: Installa cockpit-samba-manager package
      apt:
        deb: "/tmp/cockpit-samba-manager.deb"
      become: true

    - name: Aggiungi sezione registry in smb.conf
      lineinfile:
        path: "/etc/samba/smb.conf"
        line: 'include = registry'
        state: present
        insertafter: '\[global\]'
      become: true

    - name: Riavvia il servizio Samba
      service:
        name: smbd
        state: restarted
      become: true

    - name: Riavvia il servizio Cockpit
      service:
        name: cockpit.socket
        state: restarted
      become: true

    - name: Abilita e avvia il servizio Cockpit
      service:
        name: cockpit
        state: started
        enabled: true
      become: true
