- name: Update package manager
  apt:
    update_cache: true
  become: true

- name: Install packages for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
  become: true

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  become: true

- name: Add Debian 11 repository for Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present
  become: true

- name: Update package manager
  apt:
    update_cache: true
  become: true

- name: Install Docker
  apt:
    name: docker-ce
    state: present
  become: true

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present
  become: true
