- name: Create Home directory for motioneye
  file:
    path: /home/{{ utente }}/motioneye
    state: directory

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present
    
- name: Copy docker-compose.yml file
  copy:
    src: templates/docker-compose.yml
    dest: /home/{{ utente }}/motioneye/docker-compose.yml