- name: Create Home directory for dashy
  file:
    path: /home/{{ nome }}/plexserver
    state: directory

- name: Create Docker Compose file for plexserver
  copy:
    src: templates/docker-compose.yml
    dest: /home/{{ nome }}/plexserver/docker-compose.yml

