- name: Create Home directory for dashy
  file:
    path: /home/kevin/plexserver
    state: directory

- name: Create Docker Compose file for plexserver
  copy:
    src: templates/docker-compose.yml
    dest: /home/kevin/plexserver/docker-compose.yml

- name: Install plexserver using Docker Compose
  command: "docker-compose -f docker-compose.yml up -d"
  chdir: /home/kevin/plexserver