- name: Creazione di un nuovo utente
  user:
    name: "{{ utente }}"
    update_password: always
    password: "{{ password | password_hash('sha512') }}"
    groups: sudo,dialout
    createhome: true
    shell: "/bin/bash"
    state: present

- name: Configurazione dei limiti di sicurezza per l'utente
  copy:
    dest: "/etc/security/limits.d/{{ utente }}.conf"
    content: |
      {{ utente }} hard nofile 65536
      {{ utente }} soft nofile 65536
    mode: '0644'

- name: Configurazione di sudoers per l'utente e il gruppo
  lineinfile:
    path: "/etc/sudoers"
    regexp: "^(%sudo|{{ utente }})"
    line: |
      %sudo ALL=(ALL:ALL) NOPASSWD:ALL
      {{ utente }} ALL=(ALL) NOPASSWD:ALL
    validate: "visudo -cf %s"
    state: present

- name: Riavvio del servizio systemd-logind
  systemd:
    name: "systemd-logind"
    state: restarted
  when: logind_restart_required | default(true)

- name: Verifica configurazione utente
  shell: |
    echo "Test login"; whoami; cat /etc/passwd | grep "{{ utente }}"; ls -ld "/home/{{ utente }}"; ls -l /bin/bash
  register: verifica_output
  become_user: "{{ utente }}"

- debug:
    var: verifica_output.stdout
