- name: Create filemanager directory
  file:
    path: /home/kevin/filemanager
    state: directory

- name: Copy the docker-compose.yml file
  copy:
    src: templates/docker-compose.yml
    dest: /home/kevin/filemanager/docker-compose.yml
    
- name: Create filemanager container
  command: docker-compose -f docker-compose.yml up -d
  chdir: /home/kevin/filemanager