- name: Installazione di Docker
  hosts: target
  become: true
  tasks:
    - name: Aggiorna il gestore dei pacchetti
      apt:
        update_cache: true

    - name: Installa pacchetti necessari per Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Aggiungi la chiave GPG ufficiale di Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Aggiungi il repository di Docker per Debian 11
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present

    - name: Installa Docker
      apt:
        name: docker-ce
        state: present

    - name: Installa Docker Compose
      apt:
        name: docker-compose
        state: present
